// automatically generated schema, 2024-08-25T21:23:11.106Z

import { z } from "zod"

const playerMmr_SCHEMA = 
  z.union([
    z.object({
      Version: z.number(),
      Subject: z.string(),
      NewPlayerExperienceFinished: z.boolean(),
      QueueSkills: z.object({
        competitive: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                7: z.number(),
                8: z.number(),
                9: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 7: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 12: z.number(), 13: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                9: z.number(),
                10: z.number(),
                11: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4539cac3-47ae-90e5-3d01-b3812ca3274e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 13: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52ca6698-41c1-e7de-4008-8994d2221209": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                0: z.number(),
                10: z.number(),
                11: z.number(),
                13: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                0: z.number(),
                9: z.number(),
                10: z.number(),
                11: z.number(),
                12: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        deathmatch: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4539cac3-47ae-90e5-3d01-b3812ca3274e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52ca6698-41c1-e7de-4008-8994d2221209": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        hurm: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52ca6698-41c1-e7de-4008-8994d2221209": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        seeding: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        spikerush: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        swiftplay: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        unrated: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
      }),
      LatestCompetitiveUpdate: z.object({
        MatchID: z.string(),
        MapID: z.string(),
        SeasonID: z.string(),
        MatchStartTime: z.number(),
        TierAfterUpdate: z.number(),
        TierBeforeUpdate: z.number(),
        RankedRatingAfterUpdate: z.number(),
        RankedRatingBeforeUpdate: z.number(),
        RankedRatingEarned: z.number(),
        RankedRatingPerformanceBonus: z.number(),
        CompetitiveMovement: z.string(),
        AFKPenalty: z.number(),
      }),
      IsLeaderboardAnonymized: z.boolean(),
      IsActRankBadgeHidden: z.boolean(),
      OnboardingStatus: z.string(),
      OnboardingFlowV2Enabled: z.boolean(),
    }),
    z.object({
      Version: z.number(),
      Subject: z.string(),
      NewPlayerExperienceFinished: z.boolean(),
      QueueSkills: z.object({
        competitive: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 8: z.number(), 9: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                0: z.number(),
                6: z.number(),
                7: z.number(),
                8: z.number(),
                9: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 12: z.number(), 13: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                7: z.number(),
                8: z.number(),
                9: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "34093c29-4306-43de-452f-3f944bde22be": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 6: z.number(), 7: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 9: z.number(), 10: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4539cac3-47ae-90e5-3d01-b3812ca3274e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                11: z.number(),
                12: z.number(),
                13: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52ca6698-41c1-e7de-4008-8994d2221209": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                0: z.number(),
                11: z.number(),
                12: z.number(),
                13: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                0: z.number(),
                5: z.number(),
                6: z.number(),
                7: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "aca29595-40e4-01f5-3f35-b1b3d304c96e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 5: z.number(), 6: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({
                0: z.number(),
                11: z.number(),
                12: z.number(),
              }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        deathmatch: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "34093c29-4306-43de-452f-3f944bde22be": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4539cac3-47ae-90e5-3d01-b3812ca3274e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52ca6698-41c1-e7de-4008-8994d2221209": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "aca29595-40e4-01f5-3f35-b1b3d304c96e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        ggteam: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "34093c29-4306-43de-452f-3f944bde22be": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "aca29595-40e4-01f5-3f35-b1b3d304c96e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        hurm: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52ca6698-41c1-e7de-4008-8994d2221209": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        newmap: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        onefa: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "52e9749a-429b-7060-99fe-4595426a0cf7": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "aca29595-40e4-01f5-3f35-b1b3d304c96e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        premier: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        seeding: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "52e9749a-429b-7060-99fe-4595426a0cf7": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        spikerush: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "34093c29-4306-43de-452f-3f944bde22be": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52e9749a-429b-7060-99fe-4595426a0cf7": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "aca29595-40e4-01f5-3f35-b1b3d304c96e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        swiftplay: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "34093c29-4306-43de-452f-3f944bde22be": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "aca29595-40e4-01f5-3f35-b1b3d304c96e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
        unrated: z.object({
          TotalGamesNeededForRating: z.number(),
          TotalGamesNeededForLeaderboard: z.number(),
          CurrentSeasonGamesNeededForRating: z.number(),
          SeasonalInfoBySeasonID: z.object({
            "03dfd004-45d4-ebfd-ab0a-948ce780dac4": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "0981a882-4e7d-371a-70c4-c3b4f46c504a": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "22d10d66-4d2a-a340-6c54-408c7bd53807": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2a27e5d2-4d30-c9e2-b15a-93b8909a442c": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "2de5423b-4aad-02ad-8d9b-c0a931958861": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "34093c29-4306-43de-452f-3f944bde22be": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "4401f9fd-4170-2e4c-4bc3-f3b4d7d150d1": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52ca6698-41c1-e7de-4008-8994d2221209": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.null(),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "52e9749a-429b-7060-99fe-4595426a0cf7": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "9c91a445-4f78-1baa-a3ea-8f8aadf4914d": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "aca29595-40e4-01f5-3f35-b1b3d304c96e": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
            "ec876e6c-43e8-fa63-ffc1-2e8d4db25525": z.object({
              SeasonID: z.string(),
              NumberOfWins: z.number(),
              NumberOfWinsWithPlacements: z.number(),
              NumberOfGames: z.number(),
              Rank: z.number(),
              CapstoneWins: z.number(),
              LeaderboardRank: z.number(),
              CompetitiveTier: z.number(),
              RankedRating: z.number(),
              WinsByTier: z.object({ 0: z.number() }),
              GamesNeededForRating: z.number(),
              TotalWinsNeededForRank: z.number(),
            }),
          }),
        }),
      }),
      LatestCompetitiveUpdate: z.object({
        MatchID: z.string(),
        MapID: z.string(),
        SeasonID: z.string(),
        MatchStartTime: z.number(),
        TierAfterUpdate: z.number(),
        TierBeforeUpdate: z.number(),
        RankedRatingAfterUpdate: z.number(),
        RankedRatingBeforeUpdate: z.number(),
        RankedRatingEarned: z.number(),
        RankedRatingPerformanceBonus: z.number(),
        CompetitiveMovement: z.string(),
        AFKPenalty: z.number(),
      }),
      IsLeaderboardAnonymized: z.boolean(),
      IsActRankBadgeHidden: z.boolean(),
      OnboardingStatus: z.string(),
      OnboardingFlowV2Enabled: z.boolean(),
    }),
  ])


export default playerMmr_SCHEMA